Repository ni/systemlink-OpenAPI-documents, pull requests merged in 2019-10, with the labels that each got.

#63 Push changes for SystemLink 19.5
  alarm/nialarm.yml
  asset-management-rule/niapmrule.yml
  asset-managment/niapm.yml
  file/nifile.yml
  ni-notebook-execution/ninbexec.yml
  opcclient/niopcclient.yml
  systems-management/nisysmgmt.yml
  systems-state/nisystemsstate.yml
  tag-historian/nitaghistorian-cloud.yml
  tag-historian/nitaghistorian.yml
  tag/nitag.yml
  test-monitor/nitestmonitor-v1.yml
  test-monitor/nitestmonitor-v2.yml
  user-data/niuserdata.yml
Labels: systemlink-push

#64 Errors -> error
  tag-historian/nitaghistorian-cloud.yml
Labels: documentation

#65 Add apiKeyAuth to the alarm swagger doc
  alarm/nialarm.yml
Labels: codegen
