Repository ni/systemlink-OpenAPI-documents, pull requests merged in 2019-04, with the labels that each got.

#46 Push changes for SystemLink 19.0
  file/nifile.yml
  test-monitor/nitestmonitor.yml
  user-data/niuserdata.yml
Labels: systemlink-push

#48 Add API key support to Tag Historian
  tag-historian/nitaghistorian.yml
Labels: enhancement

#50 Replace 200 return codes with 204s per service changes
  message/nimessage.yml
Labels: bug
